### ISSUE TITLE
Help With Custom OSS Setup

### ISSUE THREAD

**Issue by Snipe3000** [ikrima/gamedevguide#15]
Hi @ikrima ,
Came across your custom OSS guide found here: https://ikrima.dev/ue4guide/networking/online-subsystem/using-multiple-custom-online-subsystems/

I found myself in a similar situation. We would like to setup a custom OSS to handle Oculus, Pico, Steam subsystems, ... I'm finding it difficult to start, I was hoping I can pick your brain on how to go about setting this up.

Is creating a new OnlineSubSystem class the idea? Inheriting from Epic's OnlineSubSystem.h

**Comment by ikrima** [comment]
Ah, that part is most likely very outdated since it was from the UE4.27 OSS/Oculus era. I haven't looked at the UE5 version but iirc, the new online subsystem/epic online services were rewritten to make it more friendly

fwiw, the ue4 OSS were a nightmare. We used Playfab to handle multiple systems. Hard to give a recommend since it's all very context specific to what you want to do + what's available (e.g. support steam+ps5, oculus, desktop vs mobile, support simple auth or full online services like matchmaking etc)
